apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: my-rs
spec:
  selector:
    matchLabels:
      app: team-a
  replicas: 2
  template: 
    metadata:
      name: my-pod
      labels:
        app: team-a
    spec:
      containers:
        - name: my-nginx-container
          image: nginx