apiVersion: v1
kind: Secret
metadata:
  name: app-secret
data:
  username: bGVvVg==
  password: YWRtaW4zMTM=
---
apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  restartPolicy: Never
  containers:
    - name: ubuntu-ctn
      image: ubuntu
      env:
        - name: "app_username"
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: username
        - name: "app_password"
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: password
      args:
      - env