apiVersion: v1
kind: Pod
metadata:
  name: startup-demo
spec:
  containers:
    - name: nginx-startup
      image: nginx
      startupProbe:
        httpGet:
        # dummy path to simulate a startup failure:
          # path: /dummy
          path: /
          port: 80
        periodSeconds: 5
        failureThreshold: 3