apiVersion: v1
kind: Pod
metadata:
  name: startup-demo
spec:
  containers:
    - name: nginx-startup
      image: nginx
      startupProbe:
        exec:
          command:
          # dummy command to simulate a failure
            # - "cat"
            # - "dummy.txt"
            - "cat"
            - "/usr/share/nginx/html/index.html"
        periodSeconds: 5
        failureThreshold: 3