apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-pvc
spec:
  storageClassName: standard # this is the default, it can be omitted
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5G
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
spec:
  selector:
    matchLabels:
      app: my-app
  replicas: 3
  template: 
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: nginx-cntnr
          image: nginx
          startupProbe:
            exec:
              command:
                - "bin/sh"
                - -c
                - 'echo "Hello k8s from $(hostname)</br>" >> /usr/share/nginx/html/index.html'
          volumeMounts:
            - name: pod-pvc
              mountPath: /usr/share/nginx/html
      volumes:
        - name: pod-pvc
          persistentVolumeClaim:
            claimName: my-pvc