kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: dev-cluster
nodes:
  - role: control-plane
  # neither of the below configurations work to exposer the ingress correctly
  # so apply the patch/patch.json
    # kubeadmConfigPatches:
    #   - |
    #     kind: InitConfiguration
    #     nodeRegistration:
    #       kubeletExtraArgs:
    #         node-labels: "ingress-ready=true"
    labels:
      ingress-ready: "true"
    extraPortMappings:
      - containerPort: 80
        hostPort: 80
        protocol: TCP
      - containerPort: 31234
        hostPort: 31234
        protocol: TCP
      - containerPort: 443
        hostPort: 443
        protocol: TCP
  - role: worker
  - role: worker

# 1. to start the cluster with kind:  kind create cluster --config .\resources\01-cluster.yaml
# 2. apply the nginx ingress controller yaml: kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/main/deploy/static/provider/kind/deploy.yaml
#  download and apply the nginx ingress controller yaml: curl -L -o nginx-ingress.yaml https://raw.githubusercontent.com/kubernetes/ingress-nginx/main/deploy/static/provider/kind/deploy.yaml
# 3. apply the metrics server to the cluster: kubectl apply -f .\resources\metrics-server.yaml
# 4. apply the patch.json to expose the endpoints
#  to delete the cluster:  kind delete cluster --name dev-cluster
