apiVersion: v1
kind: Pod
metadata:
  name: my-pod-1
  labels:
    dept: dept-1
    team: team-a
spec:
  containers:
    - name: my-nginx-container
      image: nginx
--- # ----------------------------------
apiVersion: v1
kind: Pod
metadata:
  name: my-pod-2
  labels:
    dept: dept-1
    team: team-b
spec:
  containers:
    - name: my-nginx-container
      image: nginx
# kubectl get pod my-pod-2 -o yaml: get the pod yaml and check its props
--- # ----------------------------------
apiVersion: v1
kind: Pod
metadata:
  name: my-pod-3
  labels:
    dept: dept-2
    team: team-a
spec:
  containers:
    - name: my-nginx-container
      image: nginx
# ----------------------------------