apiVersion: v1
kind: Pod
metadata:
  name: my-pod-1
  labels:
    dept: dept-1
    team: team-a
spec:
  containers:
    - name: my-nginx-container
      image: nginx
      # kubectl port-forward my-pod-1 80:80
      ports:
        - name: pod-port
          containerPort: 80
