apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  restartPolicy: Never
  containers:
    - name: my-ubuntu-container
      image: ubuntu
      args:
        - "/bin/bash"
        - "-c"
        - "echo Hello Kubernetes! && echo This is the current path: $PATH"