apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  restartPolicy: Never
  containers:
    - name: my-ubuntu-container
      image: ubuntu
      # override the input command
      command:
        - "date"