apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  restartPolicy: Never
  containers:
    - name: my-ubuntu-container
      image: ubuntu
      env:
        - name: "request.timeout"
          value: "100ms"
        - name: "spring.profiles.active"
          value: "dev"
      args:
        - "env"